title: "Sansiddh Jain"
author: "Sansiddh Jain"
description: "Welcome to my homepage!"
markdown: "kramdown"
more: "read more »"
url: "https://sansiddhjain.github.io/"
# baseurl: ""
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.md
  - projects.md
  - assignments.md
  - cv.md
  - blog.html
  - fun.md
  
  # - about.md

# comments:
#   disqus: "disqus-contrast"
# #  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  # - github: "https://github.com/sansiddhjain/"
  - linkedin: "https://www.linkedin.com/in/sansiddh-jain-46096a107/"
  - envelope: "mailto:sansiddh@gmail.com"
  - file: "https://sansiddhjain.github.io/cv-sansiddh.pdf"
  - twitter: "https://twitter.com/sansiddh/"
  - facebook: "https://www.facebook.com/sansiddh.jain.9/"
  - instagram: "https://www.instagram.com/not.sunsilk.or.sansad/"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
