title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
remote_theme: niklasbuschmann/contrast
more: "read more »"
# url: "https://niklasbuschmann.github.io/"
# baseurl: "/contrast"
paginate: 2
permalink: pretty
excerpt_separator: "\n\n\n" # two blank lines

style:
  minimalist: false
  dark: false

navigation:
  - index.html
  - archive.html
  - about.md

comments:
  disqus: "disqus-contrast"
#  isso: "comments.mysite.org"

links: # see http://fontawesome.io/icons/#brand for all possible icons
  - twitter: "https://twitter.com/sansiddh/"
  - github: "https://github.com/sansiddhjain"
  - envelope: "mailto:sansiddh@gmail.com"

defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
sass: {style: expanded}
plugins: [jekyll-feed, jekyll-paginate]
